chore(max-sockets): modify script

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -73,11 +73,12 @@ jobs:
   unit-tests:
     name: Unit 👷
     needs: [setup]
-    env:
-      npm_config_maxsockets: 5  # Set maxsockets to the desired value
     environment:
       name: ${{ needs.setup.outputs.environment }}
     runs-on: ubuntu-latest
+
+    env:
+      npm_config_maxsockets: 5 
 
     concurrency:
       group: unit-tests-${{ github.workflow }}-${{ github.workflow_ref }}
@@ -123,11 +124,12 @@ jobs:
   api-tests:
     name: API 👷
     needs: [setup]
-    env:
-      npm_config_maxsockets: 5  # Set maxsockets to the desired value
     environment:
       name: ${{ needs.setup.outputs.environment }}
     runs-on: ubuntu-latest
+
+    env:
+      npm_config_maxsockets: 5 
 
     concurrency:
       group: api-tests-${{ github.workflow }}-${{ github.workflow_ref }}
@@ -146,6 +148,9 @@ jobs:
         uses: actions/setup-node@v4
         with:
           node-version: ${{ vars.NODE_VERSION }}
+
+      - name: Print npm config for debugging
+        run: npm config list
 
       - name: API
         working-directory: ./
@@ -194,11 +199,12 @@ jobs:
   e2e-tests-insurance:
     name: E2E Insurance 👷
     needs: [setup]
-    env:
-      npm_config_maxsockets: 5  # Set maxsockets to the desired value
     environment:
       name: ${{ needs.setup.outputs.environment }}
     runs-on: ubuntu-latest
+
+    env:
+      npm_config_maxsockets: 5 
 
     strategy:
       # Do not cancel in-progress jobs upon failure
@@ -367,13 +373,36 @@ jobs:
         uses: actions/setup-node@v4
         with:
           node-version: ${{ vars.NODE_VERSION }}
+      
+      - name: Print npm config for debugging
+        run: npm config list
 
       - name: Dependencies
-        working-directory: ./
-        run: npm run ci:all
+      working-directory: ./
+      run: |
+        retry() {
+          local n=1
+          local max=5
+          local delay=10
+          while true; do
+            "$@" && break || {
+              if [[ $n -lt $max ]]; then
+                ((n++))
+                echo "Command failed. Attempt $n/$max:"
+                sleep $delay;
+              else
+                echo "The command has failed after $n attempts."
+                return 1
+              }
+            }
+          done
+        }
+        retry npm run ci:all
 
-      - name: Docker
-        run: docker compose up --build -d
+    - name: Docker
+      run: |
+        docker compose down --remove-orphans
+        docker compose up --build -d
 
       - name: Wait
         run: sleep 30s
@@ -438,12 +467,35 @@ jobs:
         with:
           node-version: ${{ vars.NODE_VERSION }}
 
+      - name: Print npm config for debugging
+        run: npm config list
+
       - name: Dependencies
         working-directory: ./
-        run: npm run ci:all
+        run: |
+          retry() {
+            local n=1
+            local max=5
+            local delay=10
+            while true; do
+              "$@" && break || {
+                if [[ $n -lt $max ]]; then
+                  ((n++))
+                  echo "Command failed. Attempt $n/$max:"
+                  sleep $delay;
+                else
+                  echo "The command has failed after $n attempts."
+                  return 1
+                }
+              }
+            done
+          }
+          retry npm run ci:all
 
-      - name: Docker
-        run: docker compose up --build -d
+    - name: Docker
+      run: |
+        docker compose down --remove-orphans
+        docker compose up --build -d
 
       - name: Wait
         run: sleep 30s
@@ -463,11 +515,12 @@ jobs:
   e2e-tests-switch:
     name: E2E Switch 👷
     needs: [setup]
-    env:
-      npm_config_maxsockets: 5  # Set maxsockets to the desired value
     environment:
       name: ${{ needs.setup.outputs.environment }}
     runs-on: ubuntu-latest
+
+    env:
+      npm_config_maxsockets: 5 
 
     strategy:
       # Do not cancel in-progress jobs upon failure
@@ -493,12 +546,35 @@ jobs:
         with:
           node-version: ${{ vars.NODE_VERSION }}
 
+      - name: Print npm config for debugging
+        run: npm config list
+
       - name: Dependencies
         working-directory: ./
-        run: npm run ci:all
+        run: |
+          retry() {
+            local n=1
+            local max=5
+            local delay=10
+            while true; do
+              "$@" && break || {
+                if [[ $n -lt $max ]]; then
+                  ((n++))
+                  echo "Command failed. Attempt $n/$max:"
+                  sleep $delay;
+                else
+                  echo "The command has failed after $n attempts."
+                  return 1
+                }
+              }
+            done
+          }
+          retry npm run ci:all
 
-      - name: Docker
-        run: docker compose up --build -d
+    - name: Docker
+      run: |
+        docker compose down --remove-orphans
+        docker compose up --build -d
 
       - name: Wait
         run: sleep 30s
