chore(max-sockets): modify script

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -73,10 +73,12 @@ jobs:
   unit-tests:
     name: Unit 👷
     needs: [setup]
-    env:
-      npm_config_maxsockets: 5  # Set maxsockets to the desired value
-      environment: ${{ needs.setup.outputs.environment }}
+    environment:
+      name: ${{ needs.setup.outputs.environment }}
     runs-on: ubuntu-latest
+
+    env:
+      npm_config_maxsockets: 5 
 
     concurrency:
       group: unit-tests-${{ github.workflow }}-${{ github.workflow_ref }}
@@ -122,10 +124,12 @@ jobs:
   api-tests:
     name: API 👷
     needs: [setup]
-    env:
-      npm_config_maxsockets: 5  # Set maxsockets to the desired value
-      environment: ${{ needs.setup.outputs.environment }}
+    environment:
+      name: ${{ needs.setup.outputs.environment }}
     runs-on: ubuntu-latest
+
+    env:
+      npm_config_maxsockets: 5 
 
     concurrency:
       group: api-tests-${{ github.workflow }}-${{ github.workflow_ref }}
@@ -195,10 +199,12 @@ jobs:
   e2e-tests-insurance:
     name: E2E Insurance 👷
     needs: [setup]
-    env:
-      npm_config_maxsockets: 5  # Set maxsockets to the desired value
-      environment: ${{ needs.setup.outputs.environment }}
+    environment:
+      name: ${{ needs.setup.outputs.environment }}
     runs-on: ubuntu-latest
+
+    env:
+      npm_config_maxsockets: 5 
 
     strategy:
       # Do not cancel in-progress jobs upon failure
@@ -368,30 +374,30 @@ jobs:
         with:
           node-version: ${{ vars.NODE_VERSION }}
       
-      - name: Print npm config for debugging
+            - name: Print npm config for debugging
         run: npm config list
 
       - name: Dependencies
-      working-directory: ./
-      run: |
-        retry() {
-          local n=1
-          local max=5
-          local delay=10
-          while true; do
-            "$@" && break || {
-              if [[ $n -lt $max ]]; then
-                ((n++))
-                echo "Command failed. Attempt $n/$max:"
-                sleep $delay;
-              else
-                echo "The command has failed after $n attempts."
-                return 1
+        working-directory: ./
+        run: |
+          retry() {
+            local n=1
+            local max=5
+            local delay=10
+            while true; do
+              "$@" && break || {
+                if [[ $n -lt $max ]]; then
+                  ((n++))
+                  echo "Command failed. Attempt $n/$max:"
+                  sleep $delay;
+                else
+                  echo "The command has failed after $n attempts."
+                  return 1
+                }
               }
-            }
-          done
-        }
-        retry npm run ci:all
+            done
+          }
+          retry npm run ci:all
 
     - name: Docker
       run: |
@@ -418,7 +424,8 @@ jobs:
     needs: [setup]
     env:
       npm_config_maxsockets: 5  # Set maxsockets to the desired value
-      environment: ${{ needs.setup.outputs.environment }}
+    environment:
+      name: ${{ needs.setup.outputs.environment }}
     runs-on: ubuntu-latest
 
     strategy:
@@ -508,10 +515,12 @@ jobs:
   e2e-tests-switch:
     name: E2E Switch 👷
     needs: [setup]
-    env:
-      npm_config_maxsockets: 5  # Set maxsockets to the desired value
-      environment: ${{ needs.setup.outputs.environment }}
+    environment:
+      name: ${{ needs.setup.outputs.environment }}
     runs-on: ubuntu-latest
+
+    env:
+      npm_config_maxsockets: 5 
 
     strategy:
       # Do not cancel in-progress jobs upon failure
